//
// Created by Romain on 21/07/2023.
//

////////////////////////  Includes  ///////////////////////////

#include "cpu.h"
#include "ppu.h"
#include "mmu.h"
#include "dma.h"
#include "../timer.h"


//////////////////////  Declarations  /////////////////////////

CPURegisters Registers;
u16 PCX = 0;


////////////////////////    Types   ///////////////////////////

typedef void Instruction();


////////////////////////   Macros   ///////////////////////////

#define cpu_write(addr, value) write(addr, value); sync(4)


////////////////////////   Methods   //////////////////////////

static inline void hdma_sync() {
	do {
		u8 cycles = 4; // 4 because most requires at least 2 (4 >> 1 == 2)
		dma_sync(cycles);
		
		clock_run(cycles);
		if (double_speed) cycles >>= 1;
		hdma_run(cycles);
		
		ppu_run(cycles);
		//TODO run every units here
		
	} while (hdma.general);
}

static inline void sync(u8 cycles) {
	if (hdma.general) hdma_sync();
	else {
		//if (memoryMap.bootrom_unmapped && ioTAC == 5)
		//	INFO("TM", "%02X %02X %02X %02X\n", ioDIV, ioTIMA, ioTMA, ioTAC);
		clock_run(cycles);
		dma_sync(cycles);
		
		if (double_speed) cycles >>= 1;
		
		//TODO run every units here
		ppu_run(cycles);
	}
}

static inline u8 cpu_read(u16 addr) {
	u8 r = memory_read(addr);
	sync(4);
	return r;
}

static inline u8 fetch_opcode(){
	PCX = PC;
	OPCODE = cpu_read(PC);
	if (halt_bug) halt_bug = 0; // dont increment PC once
	else PC++;
	return OPCODE;
}

static inline u8 fetch_1operand(){
	O2 = 0x00; // debug only
	return (O1 = cpu_read(PC++));
}

static inline u16 fetch_2operand(){
	O1 = cpu_read(PC++);
	O2 = cpu_read(PC++);
	return OPERAND;
}

static inline void UnknownOpcode(){
	CRITICAL("Unknown Opcode", "OPC = %02X\n", OPCODE);
}

static Instruction * HighInstructions[0x100];

#define INST(code, name) static inline void i##code()
#define INST_H(code, name) static inline void iCB##code()

#define ADD(r) u32 R = A + (r), Cx = A ^ (r) ^ R; A = R; c = Cx >> 8; z = !A; h = Cx >> 4; n = 0
#define ADC(r) u32 R = A + (r) + c, Cx = A ^ (r) ^ R; A = R; c = Cx >> 8; z = !A; h = Cx >> 4; n = 0

#define SUB(r) s32 R = A - (r), Cx = A ^ (r) ^ R; A = R; c = Cx >> 8; z = !A; h = Cx >> 4; n = 1; sync(4)
#define SBC(r) s32 R = A - (r) - c, Cx = A ^ (r) ^ R; A = R; c = Cx >> 8; z = !A; h = Cx >> 4; n = 1; sync(4)

#define ADD_SP(r) u32 Cx = SP ^ (r) ^ (SP + (r)); SP = SP + (s8)(r); c = Cx >> 8; h = Cx >> 4; z = n = 0; sync(8)
#define ADD_SP_d(r, dst) u32 Cx = SP ^ (r) ^ (SP + (r)); (dst) = SP + (s8)(r); c = Cx >> 8; h = Cx >> 4; z = n = 0; sync(4)
#define ADD_HL(r) u32 R = HL + (r), Cx = HL ^ (r) ^ R; HL = R; c = Cx >> 16; h = Cx >> 12; n = 0; sync(4)

#define INC(r) h = ((r) & 0x0F) == 0x0F; (r)++; z = !(r); n = 0
#define DEC(r) h = !((r) & 0x0F); (r)--; z = !(r); n = 1

#define AND(r) A &= (r); c = n = 0, h = 1, z = !A
#define XOR(r) A ^= (r); c = n = h = 0, z = !A
#define OR(r) A |= (r); c = n = h = 0, z = !A
#define CP(r) z = A == (r), n = 1, h = (A & 0x0F) < ((r) & 0x0F), c = A < r

#define RL(r) u8 A7 = (r) >> 7; (r) = (r) << 1 | c, c = A7, z = !(r), n = h = 0
#define RLA() u8 A7 = A >> 7; A = A << 1 | c, c = A7, z = n = h = 0
#define RLC(r) c = (r) >> 7; (r) = (r) << 1 | c, z = !(r), n = h = 0
#define RLCA() c = A >> 7; A = A << 1 | c, z = n = h = 0

#define RR(r) u8 A0 = (r) & 1; (r) = (r) >> 1 | c << 7, c = A0, z = !(r), n = h = 0
#define RRA() u8 A0 = A & 1; A = A >> 1 | c << 7, c = A0, z = n = h = 0
#define RRC(r) c = (r) & 1; (r) = (r) >> 1 | c << 7, z = !(r), n = h = 0
#define RRCA() c = A & 1; A = A >> 1 | c << 7, z = n = h = 0

#define SLA(r) c = (r) >> 7; (r) <<= 1; z = !(r), n = h = 0
#define SRA(r) c = (r) & 1; (r) = ((r) >> 1) | ((r) & 0x80); z = !(r), n = h = 0
#define SRL(r) c = (r) & 1; (r) >>= 1; z = !(r), n = h = 0

#define SWAP(r) (r) = ((r) >> 4) | ((r) << 4); z = !(r), h = c = n = 0
#define BIT(k, r) z = !(((r) >> (k)) & 1), n = 0, h = 1
#define RES(k, r) (r) &= ~(1 << (k))
#define SET(k, r) (r) |= 1 << k

#define SCF() c = 1, n = h = 0
#define CCF() c = ~c, n = h = 0
#define CPL() A = ~A, n = h = 1

#define PUSH8(r) cpu_write(--SP, (u8)(r))
//#define PUSH16(r) PUSH8((r) >> 8); PUSH8(r)
#define POP8() cpu_read(SP++)
//#define POP16() POP8() | (POP8() << 8)


static inline void PUSH16(u16 r){
	PUSH8(r >> 8);
	PUSH8(r);
}


static inline u16 POP16(){
	s32 r = POP8();
	return (u16)(r | (POP8() << 8));
}


///////////////// INSTRUCTION /////////////////

#pragma region AUTOGENERATED

#pragma region Low Instructions

INST(88, ADC_A_B) {
	ADC(B);
}  // 88 = ADC A,B	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(89, ADC_A_C) {
	ADC(C);
}  // 89 = ADC A,C	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(8A, ADC_A_D) {
	ADC(D);
}  // 8A = ADC A,D	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(8B, ADC_A_E) {
	ADC(E);
}  // 8B = ADC A,E	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(8C, ADC_A_H) {
	ADC(H);
}  // 8C = ADC A,H	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(8D, ADC_A_L) {
	ADC(L);
}  // 8D = ADC A,L	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(8E, ADC_A_(HL)) {
	u8 r = cpu_read(HL);
	ADC(r);
}  // 8E = ADC A,(HL)	 | Fg: Z 0 H C | Sz: 1 | Cc: 8

INST(8F, ADC_A_A) {
	ADC(A);
}  // 8F = ADC A,A	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(CE, ADC_A_D8) {
	ADC(O1);
}  // CE = ADC A,d8	 | Fg: Z 0 H C | Sz: 2 | Cc: 8

INST(09, ADD_HL_BC) {
	ADD_HL(BC);
}  // 09 = ADD HL,BC	 | Fg: - 0 H C | Sz: 1 | Cc: 8

INST(19, ADD_HL_DE) {
	ADD_HL(DE);
}  // 19 = ADD HL,DE	 | Fg: - 0 H C | Sz: 1 | Cc: 8

INST(29, ADD_HL_HL) {
	ADD_HL(HL);
}  // 29 = ADD HL,HL	 | Fg: - 0 H C | Sz: 1 | Cc: 8

INST(39, ADD_HL_SP) {
	ADD_HL(SP);
}  // 39 = ADD HL,SP	 | Fg: - 0 H C | Sz: 1 | Cc: 8

INST(80, ADD_A_B) {
	ADD(B);
}  // 80 = ADD A,B	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(81, ADD_A_C) {
	ADD(C);
}  // 81 = ADD A,C	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(82, ADD_A_D) {
	ADD(D);
}  // 82 = ADD A,D	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(83, ADD_A_E) {
	ADD(E);
}  // 83 = ADD A,E	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(84, ADD_A_H) {
	ADD(H);
}  // 84 = ADD A,H	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(85, ADD_A_L) {
	ADD(L);
}  // 85 = ADD A,L	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(86, ADD_A_(HL)) {
	u8 r = cpu_read(HL);
	ADD(r);
}  // 86 = ADD A,(HL)	 | Fg: Z 0 H C | Sz: 1 | Cc: 8

INST(87, ADD_A_A) {
	ADD(A);
}  // 87 = ADD A,A	 | Fg: Z 0 H C | Sz: 1 | Cc: 4

INST(C6, ADD_A_D8) {
	ADD(O1);
}  // C6 = ADD A,d8	 | Fg: Z 0 H C | Sz: 2 | Cc: 8

INST(E8, ADD_SP_R8) {
	ADD_SP(O1);
}  // E8 = ADD SP,r8	 | Fg: 0 0 H C | Sz: 2 | Cc: 16

INST(A0, AND_B) {
	AND(B);
}  // A0 = AND B	 | Fg: Z 0 1 0 | Sz: 1 | Cc: 4

INST(A1, AND_C) {
	AND(C);
}  // A1 = AND C	 | Fg: Z 0 1 0 | Sz: 1 | Cc: 4

INST(A2, AND_D) {
	AND(D);
}  // A2 = AND D	 | Fg: Z 0 1 0 | Sz: 1 | Cc: 4

INST(A3, AND_E) {
	AND(E);
}  // A3 = AND E	 | Fg: Z 0 1 0 | Sz: 1 | Cc: 4

INST(A4, AND_H) {
	AND(H);
}  // A4 = AND H	 | Fg: Z 0 1 0 | Sz: 1 | Cc: 4

INST(A5, AND_L) {
	AND(L);
}  // A5 = AND L	 | Fg: Z 0 1 0 | Sz: 1 | Cc: 4

INST(A6, AND_(HL)) {
	AND(cpu_read(HL));
}  // A6 = AND (HL)	 | Fg: Z 0 1 0 | Sz: 1 | Cc: 8

INST(A7, AND_A) {
	AND(A);
}  // A7 = AND A	 | Fg: Z 0 1 0 | Sz: 1 | Cc: 4

INST(E6, AND_D8) {
	AND(O1);
}  // E6 = AND d8	 | Fg: Z 0 1 0 | Sz: 2 | Cc: 8

INST(C4, CALL_NZ_A16) {
	if (!z) {
		PUSH16(PC);
		PC = OPERAND;
		sync(4);
	}
}  // C4 = CALL NZ,a16	 | Fg: - - - - | Sz: 3 | Cc: 24/12

INST(CC, CALL_Z_A16) {
	if (z) {
		PUSH16(PC);
		PC = OPERAND;
		sync(4);
	}
}  // CC = CALL Z,a16	 | Fg: - - - - | Sz: 3 | Cc: 24/12

INST(CD, CALL_A16) {
	PUSH16(PC);
	PC = OPERAND;
	sync(4);
}  // CD = CALL a16	 | Fg: - - - - | Sz: 3 | Cc: 24

INST(D4, CALL_NC_A16) {
	if (!c) {
		PUSH16(PC);
		PC = OPERAND;
		sync(4);
	}
}  // D4 = CALL NC,a16	 | Fg: - - - - | Sz: 3 | Cc: 24/12

INST(DC, CALL_C_A16) {
	if (c) {
		PUSH16(PC);
		PC = OPERAND;
		sync(4);
	}
}  // DC = CALL C,a16	 | Fg: - - - - | Sz: 3 | Cc: 24/12

INST(3F, CCF) {
	CCF();
}  // 3F = CCF	 | Fg: - 0 0 C | Sz: 1 | Cc: 4

INST(B8, CP_B) {
	CP(B);
}  // B8 = CP B	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(B9, CP_C) {
	CP(C);
}  // B9 = CP C	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(BA, CP_D) {
	CP(D);
}  // BA = CP D	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(BB, CP_E) {
	CP(E);
}  // BB = CP E	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(BC, CP_H) {
	CP(H);
}  // BC = CP H	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(BD, CP_L) {
	CP(L);
}  // BD = CP L	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(BE, CP_(HL)) {
	u8 r = cpu_read(HL);
	CP(r);
}  // BE = CP (HL)	 | Fg: Z 1 H C | Sz: 1 | Cc: 8

INST(BF, CP_A) {
	CP(A);
}  // BF = CP A	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(FE, CP_D8) {
	CP(O1);
}  // FE = CP d8	 | Fg: Z 1 H C | Sz: 2 | Cc: 8

INST(2F, CPL) {
	CPL();
}  // 2F = CPL	 | Fg: - 1 1 - | Sz: 1 | Cc: 4

INST(27, DAA) {
	s32 daa = A;
	if (n) {
		if (h) daa = (daa - 0x06) & 0xff;
		if (c) daa -= 0x60;
	} else {
		if (h || (daa & 0xf) > 9) daa += 0x06;
		if (c || daa > 0x9f) daa += 0x60;
	}

	A = daa, h = 0, z = !A;
	if ((daa & 0x100) == 0x100) c = 1;
}  // 27 = DAA	 | Fg: Z - 0 C | Sz: 1 | Cc: 4

INST(05, DEC_B) {
	DEC(B);
}  // 05 = DEC B	 | Fg: Z 1 H - | Sz: 1 | Cc: 4

INST(0B, DEC_BC) {
	BC--;
	sync(4);
}  // 0B = DEC BC	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(0D, DEC_C) {
	DEC(C);
}  // 0D = DEC C	 | Fg: Z 1 H - | Sz: 1 | Cc: 4

INST(15, DEC_D) {
	DEC(D);
}  // 15 = DEC D	 | Fg: Z 1 H - | Sz: 1 | Cc: 4

INST(1B, DEC_DE) {
	DE--;
	sync(4);
}  // 1B = DEC DE	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(1D, DEC_E) {
	DEC(E);
}  // 1D = DEC E	 | Fg: Z 1 H - | Sz: 1 | Cc: 4

INST(25, DEC_H) {
	DEC(H);
}  // 25 = DEC H	 | Fg: Z 1 H - | Sz: 1 | Cc: 4

INST(2B, DEC_HL) {
	HL--;
	sync(4);
}  // 2B = DEC HL	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(2D, DEC_L) {
	DEC(L);
}  // 2D = DEC L	 | Fg: Z 1 H - | Sz: 1 | Cc: 4

INST(35, DEC_(HL)) {
	u8 r = cpu_read(HL);
	DEC(r);
	cpu_write(HL, r);
}  // 35 = DEC (HL)	 | Fg: Z 1 H - | Sz: 1 | Cc: 12

INST(3B, DEC_SP) {
	SP--;
	sync(4);
}  // 3B = DEC SP	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(3D, DEC_A) {
	DEC(A);
}  // 3D = DEC A	 | Fg: Z 1 H - | Sz: 1 | Cc: 4

INST(F3, DI) {
	IME = 0;
}  // F3 = DI	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(FB, EI) {
	IME_DELAY |= 2;
}  // FB = EI	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(76, HALT) {
	if (halted) goto dec;

	if (!IME && ioIF & read_ie()) {
		if (GBC) {}
		else halt_bug = 1;
	} else {
		halted = 1;
		dec:
		PC--; // emulate halting by reexecuting halt
}
}  // 76 = HALT	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(03, INC_BC) {
	BC++;
	sync(4);
}  // 03 = INC BC	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(04, INC_B) {
	INC(B);
}  // 04 = INC B	 | Fg: Z 0 H - | Sz: 1 | Cc: 4

INST(0C, INC_C) {
	INC(C);
}  // 0C = INC C	 | Fg: Z 0 H - | Sz: 1 | Cc: 4

INST(13, INC_DE) {
	DE++;
	sync(4);
}  // 13 = INC DE	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(14, INC_D) {
	INC(D);
}  // 14 = INC D	 | Fg: Z 0 H - | Sz: 1 | Cc: 4

INST(1C, INC_E) {
	INC(E);
}  // 1C = INC E	 | Fg: Z 0 H - | Sz: 1 | Cc: 4

INST(23, INC_HL) {
	HL++;
	sync(4);
}  // 23 = INC HL	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(24, INC_H) {
	INC(H);
}  // 24 = INC H	 | Fg: Z 0 H - | Sz: 1 | Cc: 4

INST(2C, INC_L) {
	INC(L);
}  // 2C = INC L	 | Fg: Z 0 H - | Sz: 1 | Cc: 4

INST(33, INC_SP) {
	SP++;
	sync(4);
}  // 33 = INC SP	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(34, INC_(HL)) {
	u8 r = cpu_read(HL);
	INC(r);
	cpu_write(HL, r);
}  // 34 = INC (HL)	 | Fg: Z 0 H - | Sz: 1 | Cc: 12

INST(3C, INC_A) {
	INC(A);
}  // 3C = INC A	 | Fg: Z 0 H - | Sz: 1 | Cc: 4

INST(C2, JP_NZ_A16) {
	if (!z) {
		PC = OPERAND;
		sync(4);
	}
}  // C2 = JP NZ,a16	 | Fg: - - - - | Sz: 3 | Cc: 16/12

INST(C3, JP_A16) {
	PC = OPERAND;
	sync(4);
}  // C3 = JP a16	 | Fg: - - - - | Sz: 3 | Cc: 16

INST(CA, JP_Z_A16) {
	if (z) {
		PC = OPERAND;
		sync(4);
	}
}  // CA = JP Z,a16	 | Fg: - - - - | Sz: 3 | Cc: 16/12

INST(D2, JP_NC_A16) {
	if (!c) {
		PC = OPERAND;
		sync(4);
	}
}  // D2 = JP NC,a16	 | Fg: - - - - | Sz: 3 | Cc: 16/12

INST(DA, JP_C_A16) {
	if (c) {
		PC = OPERAND;
		sync(4);
	}
}  // DA = JP C,a16	 | Fg: - - - - | Sz: 3 | Cc: 16/12

INST(E9, JP_(HL)) {
	PC = HL;
}  // E9 = JP (HL)	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(18, JR_R8) {
	PC += (s8)O1;
	sync(4);
}  // 18 = JR r8	 | Fg: - - - - | Sz: 2 | Cc: 12

INST(20, JR_NZ_R8) {
	if (!z) {
		PC += (s8)O1;
		sync(4);
	}
}  // 20 = JR NZ,r8	 | Fg: - - - - | Sz: 2 | Cc: 12/8

INST(28, JR_Z_R8) {
	if (z) {
		PC += (s8)O1;
		sync(4);
	}
}  // 28 = JR Z,r8	 | Fg: - - - - | Sz: 2 | Cc: 12/8

INST(30, JR_NC_R8) {
	if (!c) {
		PC += (s8)O1;
		sync(4);
	}
}  // 30 = JR NC,r8	 | Fg: - - - - | Sz: 2 | Cc: 12/8

INST(38, JR_C_R8) {
	if (c) {
		PC += (s8)O1;
		sync(4);
	}
}  // 38 = JR C,r8	 | Fg: - - - - | Sz: 2 | Cc: 12/8

INST(01, LD_BC_D16) {
	BC = OPERAND;
}  // 01 = LD BC,d16	 | Fg: - - - - | Sz: 3 | Cc: 12

INST(02, LD_(BC)_A) {
	cpu_write(BC, A);
}  // 02 = LD (BC),A	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(06, LD_B_D8) {
	B = O1;
}  // 06 = LD B,d8	 | Fg: - - - - | Sz: 2 | Cc: 8

INST(08, LD_(A16)_SP) {
	cpu_write(OPERAND, SP);
	cpu_write(OPERAND + 1, SP >> 8);
}  // 08 = LD (a16),SP	 | Fg: - - - - | Sz: 3 | Cc: 20

INST(0A, LD_A_(BC)) {
	A = cpu_read(BC);
}  // 0A = LD A,(BC)	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(0E, LD_C_D8) {
	C = O1;
}  // 0E = LD C,d8	 | Fg: - - - - | Sz: 2 | Cc: 8

INST(11, LD_DE_D16) {
	DE = OPERAND;
}  // 11 = LD DE,d16	 | Fg: - - - - | Sz: 3 | Cc: 12

INST(12, LD_(DE)_A) {
	cpu_write(DE, A);
}  // 12 = LD (DE),A	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(16, LD_D_D8) {
	D = O1;
}  // 16 = LD D,d8	 | Fg: - - - - | Sz: 2 | Cc: 8

INST(1A, LD_A_(DE)) {
	A = cpu_read(DE);
}  // 1A = LD A,(DE)	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(1E, LD_E_D8) {
	E = O1;
}  // 1E = LD E,d8	 | Fg: - - - - | Sz: 2 | Cc: 8

INST(21, LD_HL_D16) {
	HL = OPERAND;
}  // 21 = LD HL,d16	 | Fg: - - - - | Sz: 3 | Cc: 12

INST(22, LD_(HL_)_A) {
	cpu_write(HL++, A);
}  // 22 = LD (HL+),A	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(26, LD_H_D8) {
	H = O1;
}  // 26 = LD H,d8	 | Fg: - - - - | Sz: 2 | Cc: 8

INST(2A, LD_A_(HL_)) {
	A = cpu_read(HL++);
}  // 2A = LD A,(HL+)	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(2E, LD_L_D8) {
	L = O1;
}  // 2E = LD L,d8	 | Fg: - - - - | Sz: 2 | Cc: 8

INST(31, LD_SP_D16) {
	SP = OPERAND;
}  // 31 = LD SP,d16	 | Fg: - - - - | Sz: 3 | Cc: 12

INST(32, LD_(HL-)_A) {
	cpu_write(HL--, A);
}  // 32 = LD (HL-),A	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(36, LD_(HL)_D8) {
	cpu_write(HL, O1);
}  // 36 = LD (HL),d8	 | Fg: - - - - | Sz: 2 | Cc: 12

INST(3A, LD_A_(HL-)) {
	A = cpu_read(HL--);
}  // 3A = LD A,(HL-)	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(3E, LD_A_D8) {
	A = O1;
}  // 3E = LD A,d8	 | Fg: - - - - | Sz: 2 | Cc: 8

INST(40, LD_B_B) {
	B = B;
}  // 40 = LD B,B	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(41, LD_B_C) {
	B = C;
}  // 41 = LD B,C	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(42, LD_B_D) {
	B = D;
}  // 42 = LD B,D	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(43, LD_B_E) {
	B = E;
}  // 43 = LD B,E	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(44, LD_B_H) {
	B = H;
}  // 44 = LD B,H	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(45, LD_B_L) {
	B = L;
}  // 45 = LD B,L	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(46, LD_B_(HL)) {
	B = cpu_read(HL);
}  // 46 = LD B,(HL)	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(47, LD_B_A) {
	B = A;
}  // 47 = LD B,A	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(48, LD_C_B) {
	C = B;
}  // 48 = LD C,B	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(49, LD_C_C) {
	C = C;
}  // 49 = LD C,C	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(4A, LD_C_D) {
	C = D;
}  // 4A = LD C,D	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(4B, LD_C_E) {
	C = E;
}  // 4B = LD C,E	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(4C, LD_C_H) {
	C = H;
}  // 4C = LD C,H	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(4D, LD_C_L) {
	C = L;
}  // 4D = LD C,L	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(4E, LD_C_(HL)) {
	C = cpu_read(HL);
}  // 4E = LD C,(HL)	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(4F, LD_C_A) {
	C = A;
}  // 4F = LD C,A	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(50, LD_D_B) {
	D = B;
}  // 50 = LD D,B	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(51, LD_D_C) {
	D = C;
}  // 51 = LD D,C	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(52, LD_D_D) {
	D = D;
}  // 52 = LD D,D	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(53, LD_D_E) {
	D = E;
}  // 53 = LD D,E	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(54, LD_D_H) {
	D = H;
}  // 54 = LD D,H	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(55, LD_D_L) {
	D = L;
}  // 55 = LD D,L	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(56, LD_D_(HL)) {
	D = cpu_read(HL);
}  // 56 = LD D,(HL)	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(57, LD_D_A) {
	D = A;
}  // 57 = LD D,A	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(58, LD_E_B) {
	E = B;
}  // 58 = LD E,B	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(59, LD_E_C) {
	E = C;
}  // 59 = LD E,C	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(5A, LD_E_D) {
	E = D;
}  // 5A = LD E,D	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(5B, LD_E_E) {
	E = E;
}  // 5B = LD E,E	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(5C, LD_E_H) {
	E = H;
}  // 5C = LD E,H	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(5D, LD_E_L) {
	E = L;
}  // 5D = LD E,L	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(5E, LD_E_(HL)) {
	E = cpu_read(HL);
}  // 5E = LD E,(HL)	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(5F, LD_E_A) {
	E = A;
}  // 5F = LD E,A	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(60, LD_H_B) {
	H = B;
}  // 60 = LD H,B	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(61, LD_H_C) {
	H = C;
}  // 61 = LD H,C	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(62, LD_H_D) {
	H = D;
}  // 62 = LD H,D	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(63, LD_H_E) {
	H = E;
}  // 63 = LD H,E	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(64, LD_H_H) {
	H = H;
}  // 64 = LD H,H	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(65, LD_H_L) {
	H = L;
}  // 65 = LD H,L	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(66, LD_H_(HL)) {
	H = cpu_read(HL);
}  // 66 = LD H,(HL)	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(67, LD_H_A) {
	H = A;
}  // 67 = LD H,A	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(68, LD_L_B) {
	L = B;
}  // 68 = LD L,B	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(69, LD_L_C) {
	L = C;
}  // 69 = LD L,C	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(6A, LD_L_D) {
	L = D;
}  // 6A = LD L,D	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(6B, LD_L_E) {
	L = E;
}  // 6B = LD L,E	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(6C, LD_L_H) {
	L = H;
}  // 6C = LD L,H	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(6D, LD_L_L) {
	L = L;
}  // 6D = LD L,L	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(6E, LD_L_(HL)) {
	L = cpu_read(HL);
}  // 6E = LD L,(HL)	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(6F, LD_L_A) {
	L = A;
}  // 6F = LD L,A	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(70, LD_(HL)_B) {
	cpu_write(HL, B);
}  // 70 = LD (HL),B	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(71, LD_(HL)_C) {
	cpu_write(HL, C);
}  // 71 = LD (HL),C	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(72, LD_(HL)_D) {
	cpu_write(HL, D);
}  // 72 = LD (HL),D	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(73, LD_(HL)_E) {
	cpu_write(HL, E);
}  // 73 = LD (HL),E	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(74, LD_(HL)_H) {
	cpu_write(HL, H);
}  // 74 = LD (HL),H	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(75, LD_(HL)_L) {
	cpu_write(HL, L);
}  // 75 = LD (HL),L	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(77, LD_(HL)_A) {
	cpu_write(HL, A);
}  // 77 = LD (HL),A	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(78, LD_A_B) {
	A = B;
}  // 78 = LD A,B	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(79, LD_A_C) {
	A = C;
}  // 79 = LD A,C	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(7A, LD_A_D) {
	A = D;
}  // 7A = LD A,D	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(7B, LD_A_E) {
	A = E;
}  // 7B = LD A,E	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(7C, LD_A_H) {
	A = H;
}  // 7C = LD A,H	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(7D, LD_A_L) {
	A = L;
}  // 7D = LD A,L	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(7E, LD_A_(HL)) {
	A = cpu_read(HL);
}  // 7E = LD A,(HL)	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(7F, LD_A_A) {
	A = A;
}  // 7F = LD A,A	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(E2, LD_(C)_A) {
	cpu_write(0xFF00 | C, A);
}  // E2 = LD (C),A	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(EA, LD_(A16)_A) {
	cpu_write(OPERAND, A);
}  // EA = LD (a16),A	 | Fg: - - - - | Sz: 3 | Cc: 16

INST(F2, LD_A_(C)) {
	A = cpu_read(0xFF00 | C);
}  // F2 = LD A,(C)	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(F8, LD_HL_SP_R8) {
	ADD_SP_d(O1, HL);
}  // F8 = LD HL,SP+r8	 | Fg: 0 0 H C | Sz: 2 | Cc: 12

INST(F9, LD_SP_HL) {
	SP = HL;
	sync(4);
}  // F9 = LD SP,HL	 | Fg: - - - - | Sz: 1 | Cc: 8

INST(FA, LD_A_(A16)) {
	A = cpu_read(OPERAND);
}  // FA = LD A,(a16)	 | Fg: - - - - | Sz: 3 | Cc: 16

INST(E0, LDH_(A8)_A) {
	cpu_write(0xFF00 | O1, A);
}  // E0 = LDH (a8),A	 | Fg: - - - - | Sz: 2 | Cc: 12

INST(F0, LDH_A_(A8)) {
	A = cpu_read(0xFF00 | O1);
}  // F0 = LDH A,(a8)	 | Fg: - - - - | Sz: 2 | Cc: 12

INST(00, NOP) {
}  // 00 = NOP	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(B0, OR_B) {
	OR(B);
}  // B0 = OR B	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(B1, OR_C) {
	OR(C);
}  // B1 = OR C	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(B2, OR_D) {
	OR(D);
}  // B2 = OR D	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(B3, OR_E) {
	OR(E);
}  // B3 = OR E	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(B4, OR_H) {
	OR(H);
}  // B4 = OR H	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(B5, OR_L) {
	OR(L);
}  // B5 = OR L	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(B6, OR_(HL)) {
	OR(cpu_read(HL));
}  // B6 = OR (HL)	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 8

INST(B7, OR_A) {
	OR(A);
}  // B7 = OR A	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(F6, OR_D8) {
	OR(O1);
}  // F6 = OR d8	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST(C1, POP_BC) {
	BC = POP16();
}  // C1 = POP BC	 | Fg: - - - - | Sz: 1 | Cc: 12

INST(D1, POP_DE) {
	DE = POP16();
}  // D1 = POP DE	 | Fg: - - - - | Sz: 1 | Cc: 12

INST(E1, POP_HL) {
	HL = POP16();
}  // E1 = POP HL	 | Fg: - - - - | Sz: 1 | Cc: 12

INST(F1, POP_AF) {
	AF = POP16();
	Fx = 0;
}  // F1 = POP AF	 | Fg: Z N H C | Sz: 1 | Cc: 12

INST(CB, PREFIX_CB) {
	HighInstructions[O1]();
} // CB = PREFIX CB	 | Fg: - - - - | Sz: 2 | Cc: 4

INST(C5, PUSH_BC) {
	PUSH16(BC);
	sync(4);
}  // C5 = PUSH BC	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(D5, PUSH_DE) {
	PUSH16(DE);
	sync(4);
}  // D5 = PUSH DE	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(E5, PUSH_HL) {
	PUSH16(HL);
	sync(4);
}  // E5 = PUSH HL	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(F5, PUSH_AF) {
	PUSH16(AF);
	sync(4);
}  // F5 = PUSH AF	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(C0, RET_NZ) {
	sync(4);
	if (!z) {
		PC = POP16();
		sync(4);
	}
}  // C0 = RET NZ	 | Fg: - - - - | Sz: 1 | Cc: 20/8

INST(C8, RET_Z) {
	sync(4);
	if (z) {
		PC = POP16();
		sync(4);
	}
}  // C8 = RET Z	 | Fg: - - - - | Sz: 1 | Cc: 20/8

INST(C9, RET) {
	PC = POP16();
	sync(4);
}  // C9 = RET	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(D0, RET_NC) {
	sync(4);
	if (!c) {
		PC = POP16();
		sync(4);
	}
}  // D0 = RET NC	 | Fg: - - - - | Sz: 1 | Cc: 20/8

INST(D8, RET_C) {
	sync(4);
	if (c) {
		PC = POP16();
		sync(4);
	}
}  // D8 = RET C	 | Fg: - - - - | Sz: 1 | Cc: 20/8

INST(D9, RETI) {
	PC = POP16();
	sync(4);
	IME = 1;
}  // D9 = RETI	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(17, RLA) {
	RLA();
}  // 17 = RLA	 | Fg: 0 0 0 C | Sz: 1 | Cc: 4

INST(07, RLCA) {
	RLCA();
}  // 07 = RLCA	 | Fg: 0 0 0 C | Sz: 1 | Cc: 4

INST(1F, RRA) {
	RRA();
}  // 1F = RRA	 | Fg: 0 0 0 C | Sz: 1 | Cc: 4

INST(0F, RRCA) {
	RRCA();
}  // 0F = RRCA	 | Fg: 0 0 0 C | Sz: 1 | Cc: 4

INST(C7, RST_00H) {
	PUSH16(PC);
	PC = 0x00;
	sync(4);
}  // C7 = RST 00H	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(CF, RST_08H) {
	PUSH16(PC);
	PC = 0x08;
	sync(4);
}  // CF = RST 08H	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(D7, RST_10H) {
	PUSH16(PC);
	PC = 0x10;
	sync(4);
}  // D7 = RST 10H	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(DF, RST_18H) {
	PUSH16(PC);
	PC = 0x18;
	sync(4);
}  // DF = RST 18H	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(E7, RST_20H) {
	PUSH16(PC);
	PC = 0x20;
	sync(4);
}  // E7 = RST 20H	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(EF, RST_28H) {
	PUSH16(PC);
	PC = 0x28;
	sync(4);
}  // EF = RST 28H	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(F7, RST_30H) {
	PUSH16(PC);
	PC = 0x30;
	sync(4);
}  // F7 = RST 30H	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(FF, RST_38H) {
	PUSH16(PC);
	PC = 0x38;
	sync(4);
}  // FF = RST 38H	 | Fg: - - - - | Sz: 1 | Cc: 16

INST(98, SBC_A_B) {
	SBC(B);
}  // 98 = SBC A,B	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(99, SBC_A_C) {
	SBC(C);
}  // 99 = SBC A,C	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(9A, SBC_A_D) {
	SBC(D);
}  // 9A = SBC A,D	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(9B, SBC_A_E) {
	SBC(E);
}  // 9B = SBC A,E	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(9C, SBC_A_H) {
	SBC(H);
}  // 9C = SBC A,H	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(9D, SBC_A_L) {
	SBC(L);
}  // 9D = SBC A,L	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(9E, SBC_A_(HL)) {
	u8 r = cpu_read(HL);
	SBC(r);
}  // 9E = SBC A,(HL)	 | Fg: Z 1 H C | Sz: 1 | Cc: 8

INST(9F, SBC_A_A) {
	SBC(A);
}  // 9F = SBC A,A	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(DE, SBC_A_D8) {
	SBC(O1);
}  // DE = SBC A,d8	 | Fg: Z 1 H C | Sz: 2 | Cc: 8

INST(37, SCF) {
	SCF();
}  // 37 = SCF	 | Fg: - 0 0 1 | Sz: 1 | Cc: 4

INST(10, STOP_0) {

	if ((~ioJOYP) & 0x0F){ // Btn selected
		if (ioIF & read_ie()) {
		
		} else {
			PC++;
			ERROR("STOP Instruction - HALT Mode entrance", "unimplemented\n");
			halted = 1;
		}
	} else {
		if ((ioKEY1 & 1) && GBC) {
			if (ioIF & read_ie()) {
				if (IME) {
					ERROR("STOP Instruction error", "non-deterministic crash\n");
					// glitch
				} else {
					ch_speed:
					double_speed = !double_speed;
					write_io(KEY1, 0);
					// TODO: Reset DIV
				}
			} else {
				PC++;
				ERROR("STOP Instruction - Special HALT Mode entrance", "unimplemented\n");
				// halted = 1; ???
				goto ch_speed;
			}
		} else {
			if (!(ioIF & read_ie())) PC++;
			ERROR("STOP Instruction - STOP Mode entrance", "unimplemented\n");
			// STOP Mode
			// TODO: Reset DIV
		}
	}

	}  // 10 = STOP 0	 | Fg: - - - - | Sz: 1 | Cc: 4

INST(90, SUB_B) {
	SUB(B);
}  // 90 = SUB B	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(91, SUB_C) {
	SUB(C);
}  // 91 = SUB C	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(92, SUB_D) {
	SUB(D);
}  // 92 = SUB D	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(93, SUB_E) {
	SUB(E);
}  // 93 = SUB E	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(94, SUB_H) {
	SUB(H);
}  // 94 = SUB H	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(95, SUB_L) {
	SUB(L);
}  // 95 = SUB L	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(96, SUB_(HL)) {
	u8 r = cpu_read(HL);
	SUB(r);
}  // 96 = SUB (HL)	 | Fg: Z 1 H C | Sz: 1 | Cc: 8

INST(97, SUB_A) {
	SUB(A);
}  // 97 = SUB A	 | Fg: Z 1 H C | Sz: 1 | Cc: 4

INST(D6, SUB_D8) {
	SUB(O1);
}  // D6 = SUB d8	 | Fg: Z 1 H C | Sz: 2 | Cc: 8
#define iD3 UnknownOpcode
#define iDB UnknownOpcode
#define iDD UnknownOpcode
#define iE3 UnknownOpcode
#define iE4 UnknownOpcode
#define iEB UnknownOpcode
#define iEC UnknownOpcode
#define iED UnknownOpcode
#define iF4 UnknownOpcode
#define iFC UnknownOpcode
#define iFD UnknownOpcode

INST(A8, XOR_B) {
	XOR(B);
}  // A8 = XOR B	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(A9, XOR_C) {
	XOR(C);
}  // A9 = XOR C	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(AA, XOR_D) {
	XOR(D);
}  // AA = XOR D	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(AB, XOR_E) {
	XOR(E);
}  // AB = XOR E	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(AC, XOR_H) {
	XOR(H);
}  // AC = XOR H	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(AD, XOR_L) {
	XOR(L);
}  // AD = XOR L	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(AE, XOR_(HL)) {
	XOR(cpu_read(HL));
}  // AE = XOR (HL)	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 8

INST(AF, XOR_A) {
	XOR(A);
}  // AF = XOR A	 | Fg: Z 0 0 0 | Sz: 1 | Cc: 4

INST(EE, XOR_D8) {
	XOR(O1);
}  // EE = XOR d8	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

#pragma endregion

#pragma region High Instructions

INST_H(40, BIT_0_B) {
	BIT(0, B);
}  // 40 = BIT 0,B	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(41, BIT_0_C) {
	BIT(0, C);
}  // 41 = BIT 0,C	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(42, BIT_0_D) {
	BIT(0, D);
}  // 42 = BIT 0,D	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(43, BIT_0_E) {
	BIT(0, E);
}  // 43 = BIT 0,E	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(44, BIT_0_H) {
	BIT(0, H);
}  // 44 = BIT 0,H	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(45, BIT_0_L) {
	BIT(0, L);
}  // 45 = BIT 0,L	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(46, BIT_0_(HL)) {
	u8 r = cpu_read(HL);
	BIT(0, r);
}  // 46 = BIT 0,(HL)	 | Fg: Z 0 1 - | Sz: 2 | Cc: 12

INST_H(47, BIT_0_A) {
	BIT(0, A);
}  // 47 = BIT 0,A	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(48, BIT_1_B) {
	BIT(1, B);
}  // 48 = BIT 1,B	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(49, BIT_1_C) {
	BIT(1, C);
}  // 49 = BIT 1,C	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(4A, BIT_1_D) {
	BIT(1, D);
}  // 4A = BIT 1,D	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(4B, BIT_1_E) {
	BIT(1, E);
}  // 4B = BIT 1,E	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(4C, BIT_1_H) {
	BIT(1, H);
}  // 4C = BIT 1,H	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(4D, BIT_1_L) {
	BIT(1, L);
}  // 4D = BIT 1,L	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(4E, BIT_1_(HL)) {
	u8 r = cpu_read(HL);
	BIT(1, r);
}  // 4E = BIT 1,(HL)	 | Fg: Z 0 1 - | Sz: 2 | Cc: 12

INST_H(4F, BIT_1_A) {
	BIT(1, A);
}  // 4F = BIT 1,A	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(50, BIT_2_B) {
	BIT(2, B);
}  // 50 = BIT 2,B	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(51, BIT_2_C) {
	BIT(2, C);
}  // 51 = BIT 2,C	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(52, BIT_2_D) {
	BIT(2, D);
}  // 52 = BIT 2,D	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(53, BIT_2_E) {
	BIT(2, E);
}  // 53 = BIT 2,E	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(54, BIT_2_H) {
	BIT(2, H);
}  // 54 = BIT 2,H	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(55, BIT_2_L) {
	BIT(2, L);
}  // 55 = BIT 2,L	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(56, BIT_2_(HL)) {
	u8 r = cpu_read(HL);
	BIT(2, r);
}  // 56 = BIT 2,(HL)	 | Fg: Z 0 1 - | Sz: 2 | Cc: 12

INST_H(57, BIT_2_A) {
	BIT(2, A);
}  // 57 = BIT 2,A	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(58, BIT_3_B) {
	BIT(3, B);
}  // 58 = BIT 3,B	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(59, BIT_3_C) {
	BIT(3, C);
}  // 59 = BIT 3,C	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(5A, BIT_3_D) {
	BIT(3, D);
}  // 5A = BIT 3,D	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(5B, BIT_3_E) {
	BIT(3, E);
}  // 5B = BIT 3,E	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(5C, BIT_3_H) {
	BIT(3, H);
}  // 5C = BIT 3,H	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(5D, BIT_3_L) {
	BIT(3, L);
}  // 5D = BIT 3,L	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(5E, BIT_3_(HL)) {
	u8 r = cpu_read(HL);
	BIT(3, r);
}  // 5E = BIT 3,(HL)	 | Fg: Z 0 1 - | Sz: 2 | Cc: 12

INST_H(5F, BIT_3_A) {
	BIT(3, A);
}  // 5F = BIT 3,A	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(60, BIT_4_B) {
	BIT(4, B);
}  // 60 = BIT 4,B	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(61, BIT_4_C) {
	BIT(4, C);
}  // 61 = BIT 4,C	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(62, BIT_4_D) {
	BIT(4, D);
}  // 62 = BIT 4,D	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(63, BIT_4_E) {
	BIT(4, E);
}  // 63 = BIT 4,E	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(64, BIT_4_H) {
	BIT(4, H);
}  // 64 = BIT 4,H	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(65, BIT_4_L) {
	BIT(4, L);
}  // 65 = BIT 4,L	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(66, BIT_4_(HL)) {
	u8 r = cpu_read(HL);
	BIT(4, r);
}  // 66 = BIT 4,(HL)	 | Fg: Z 0 1 - | Sz: 2 | Cc: 12

INST_H(67, BIT_4_A) {
	BIT(4, A);
}  // 67 = BIT 4,A	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(68, BIT_5_B) {
	BIT(5, B);
}  // 68 = BIT 5,B	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(69, BIT_5_C) {
	BIT(5, C);
}  // 69 = BIT 5,C	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(6A, BIT_5_D) {
	BIT(5, D);
}  // 6A = BIT 5,D	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(6B, BIT_5_E) {
	BIT(5, E);
}  // 6B = BIT 5,E	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(6C, BIT_5_H) {
	BIT(5, H);
}  // 6C = BIT 5,H	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(6D, BIT_5_L) {
	BIT(5, L);
}  // 6D = BIT 5,L	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(6E, BIT_5_(HL)) {
	u8 r = cpu_read(HL);
	BIT(5, r);
}  // 6E = BIT 5,(HL)	 | Fg: Z 0 1 - | Sz: 2 | Cc: 12

INST_H(6F, BIT_5_A) {
	BIT(5, A);
}  // 6F = BIT 5,A	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(70, BIT_6_B) {
	BIT(6, B);
}  // 70 = BIT 6,B	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(71, BIT_6_C) {
	BIT(6, C);
}  // 71 = BIT 6,C	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(72, BIT_6_D) {
	BIT(6, D);
}  // 72 = BIT 6,D	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(73, BIT_6_E) {
	BIT(6, E);
}  // 73 = BIT 6,E	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(74, BIT_6_H) {
	BIT(6, H);
}  // 74 = BIT 6,H	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(75, BIT_6_L) {
	BIT(6, L);
}  // 75 = BIT 6,L	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(76, BIT_6_(HL)) {
	u8 r = cpu_read(HL);
	BIT(6, r);
}  // 76 = BIT 6,(HL)	 | Fg: Z 0 1 - | Sz: 2 | Cc: 12

INST_H(77, BIT_6_A) {
	BIT(6, A);
}  // 77 = BIT 6,A	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(78, BIT_7_B) {
	BIT(7, B);
}  // 78 = BIT 7,B	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(79, BIT_7_C) {
	BIT(7, C);
}  // 79 = BIT 7,C	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(7A, BIT_7_D) {
	BIT(7, D);
}  // 7A = BIT 7,D	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(7B, BIT_7_E) {
	BIT(7, E);
}  // 7B = BIT 7,E	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(7C, BIT_7_H) {
	BIT(7, H);
}  // 7C = BIT 7,H	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(7D, BIT_7_L) {
	BIT(7, L);
}  // 7D = BIT 7,L	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(7E, BIT_7_(HL)) {
	u8 r = cpu_read(HL);
	BIT(7, r);
}  // 7E = BIT 7,(HL)	 | Fg: Z 0 1 - | Sz: 2 | Cc: 12

INST_H(7F, BIT_7_A) {
	BIT(7, A);
}  // 7F = BIT 7,A	 | Fg: Z 0 1 - | Sz: 2 | Cc: 8

INST_H(80, RES_0_B) {
	RES(0, B);
}  // 80 = RES 0,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(81, RES_0_C) {
	RES(0, C);
}  // 81 = RES 0,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(82, RES_0_D) {
	RES(0, D);
}  // 82 = RES 0,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(83, RES_0_E) {
	RES(0, E);
}  // 83 = RES 0,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(84, RES_0_H) {
	RES(0, H);
}  // 84 = RES 0,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(85, RES_0_L) {
	RES(0, L);
}  // 85 = RES 0,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(86, RES_0_(HL)) {
	u8 r = cpu_read(HL);
	RES(0, r);
	cpu_write(HL, r);
}  // 86 = RES 0,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(87, RES_0_A) {
	RES(0, A);
}  // 87 = RES 0,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(88, RES_1_B) {
	RES(1, B);
}  // 88 = RES 1,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(89, RES_1_C) {
	RES(1, C);
}  // 89 = RES 1,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(8A, RES_1_D) {
	RES(1, D);
}  // 8A = RES 1,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(8B, RES_1_E) {
	RES(1, E);
}  // 8B = RES 1,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(8C, RES_1_H) {
	RES(1, H);
}  // 8C = RES 1,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(8D, RES_1_L) {
	RES(1, L);
}  // 8D = RES 1,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(8E, RES_1_(HL)) {
	u8 r = cpu_read(HL);
	RES(1, r);
	cpu_write(HL, r);
}  // 8E = RES 1,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(8F, RES_1_A) {
	RES(1, A);
}  // 8F = RES 1,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(90, RES_2_B) {
	RES(2, B);
}  // 90 = RES 2,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(91, RES_2_C) {
	RES(2, C);
}  // 91 = RES 2,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(92, RES_2_D) {
	RES(2, D);
}  // 92 = RES 2,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(93, RES_2_E) {
	RES(2, E);
}  // 93 = RES 2,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(94, RES_2_H) {
	RES(2, H);
}  // 94 = RES 2,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(95, RES_2_L) {
	RES(2, L);
}  // 95 = RES 2,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(96, RES_2_(HL)) {
	u8 r = cpu_read(HL);
	RES(2, r);
	cpu_write(HL, r);
}  // 96 = RES 2,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(97, RES_2_A) {
	RES(2, A);
}  // 97 = RES 2,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(98, RES_3_B) {
	RES(3, B);
}  // 98 = RES 3,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(99, RES_3_C) {
	RES(3, C);
}  // 99 = RES 3,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(9A, RES_3_D) {
	RES(3, D);
}  // 9A = RES 3,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(9B, RES_3_E) {
	RES(3, E);
}  // 9B = RES 3,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(9C, RES_3_H) {
	RES(3, H);
}  // 9C = RES 3,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(9D, RES_3_L) {
	RES(3, L);
}  // 9D = RES 3,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(9E, RES_3_(HL)) {
	u8 r = cpu_read(HL);
	RES(3, r);
	cpu_write(HL, r);
}  // 9E = RES 3,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(9F, RES_3_A) {
	RES(3, A);
}  // 9F = RES 3,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(A0, RES_4_B) {
	RES(4, B);
}  // A0 = RES 4,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(A1, RES_4_C) {
	RES(4, C);
}  // A1 = RES 4,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(A2, RES_4_D) {
	RES(4, D);
}  // A2 = RES 4,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(A3, RES_4_E) {
	RES(4, E);
}  // A3 = RES 4,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(A4, RES_4_H) {
	RES(4, H);
}  // A4 = RES 4,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(A5, RES_4_L) {
	RES(4, L);
}  // A5 = RES 4,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(A6, RES_4_(HL)) {
	u8 r = cpu_read(HL);
	RES(4, r);
	cpu_write(HL, r);
}  // A6 = RES 4,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(A7, RES_4_A) {
	RES(4, A);
}  // A7 = RES 4,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(A8, RES_5_B) {
	RES(5, B);
}  // A8 = RES 5,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(A9, RES_5_C) {
	RES(5, C);
}  // A9 = RES 5,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(AA, RES_5_D) {
	RES(5, D);
}  // AA = RES 5,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(AB, RES_5_E) {
	RES(5, E);
}  // AB = RES 5,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(AC, RES_5_H) {
	RES(5, H);
}  // AC = RES 5,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(AD, RES_5_L) {
	RES(5, L);
}  // AD = RES 5,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(AE, RES_5_(HL)) {
	u8 r = cpu_read(HL);
	RES(5, r);
	cpu_write(HL, r);
}  // AE = RES 5,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(AF, RES_5_A) {
	RES(5, A);
}  // AF = RES 5,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(B0, RES_6_B) {
	RES(6, B);
}  // B0 = RES 6,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(B1, RES_6_C) {
	RES(6, C);
}  // B1 = RES 6,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(B2, RES_6_D) {
	RES(6, D);
}  // B2 = RES 6,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(B3, RES_6_E) {
	RES(6, E);
}  // B3 = RES 6,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(B4, RES_6_H) {
	RES(6, H);
}  // B4 = RES 6,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(B5, RES_6_L) {
	RES(6, L);
}  // B5 = RES 6,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(B6, RES_6_(HL)) {
	u8 r = cpu_read(HL);
	RES(6, r);
	cpu_write(HL, r);
}  // B6 = RES 6,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(B7, RES_6_A) {
	RES(6, A);
}  // B7 = RES 6,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(B8, RES_7_B) {
	RES(7, B);
}  // B8 = RES 7,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(B9, RES_7_C) {
	RES(7, C);
}  // B9 = RES 7,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(BA, RES_7_D) {
	RES(7, D);
}  // BA = RES 7,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(BB, RES_7_E) {
	RES(7, E);
}  // BB = RES 7,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(BC, RES_7_H) {
	RES(7, H);
}  // BC = RES 7,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(BD, RES_7_L) {
	RES(7, L);
}  // BD = RES 7,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(BE, RES_7_(HL)) {
	u8 r = cpu_read(HL);
	RES(7, r);
	cpu_write(HL, r);
}  // BE = RES 7,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(BF, RES_7_A) {
	RES(7, A);
}  // BF = RES 7,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(10, RL_B) {
	RL(B);
}  // 10 = RL B	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(11, RL_C) {
	RL(C);
}  // 11 = RL C	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(12, RL_D) {
	RL(D);
}  // 12 = RL D	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(13, RL_E) {
	RL(E);
}  // 13 = RL E	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(14, RL_H) {
	RL(H);
}  // 14 = RL H	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(15, RL_L) {
	RL(L);
}  // 15 = RL L	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(16, RL_(HL)) {
	u8 r = cpu_read(HL);
	RL(r);
	cpu_write(HL, r);
}  // 16 = RL (HL)	 | Fg: Z 0 0 C | Sz: 2 | Cc: 16

INST_H(17, RL_A) {
	RL(A);
}  // 17 = RL A	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(00, RLC_B) {
	RLC(B);
}  // 00 = RLC B	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(01, RLC_C) {
	RLC(C);
}  // 01 = RLC C	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(02, RLC_D) {
	RLC(D);
}  // 02 = RLC D	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(03, RLC_E) {
	RLC(E);
}  // 03 = RLC E	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(04, RLC_H) {
	RLC(H);
}  // 04 = RLC H	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(05, RLC_L) {
	RLC(L);
}  // 05 = RLC L	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(06, RLC_(HL)) {
	u8 r = cpu_read(HL);
	RLC(r);
	cpu_write(HL, r);
}  // 06 = RLC (HL)	 | Fg: Z 0 0 C | Sz: 2 | Cc: 16

INST_H(07, RLC_A) {
	RLC(A);
}  // 07 = RLC A	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(18, RR_B) {
	RR(B);
}  // 18 = RR B	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(19, RR_C) {
	RR(C);
}  // 19 = RR C	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(1A, RR_D) {
	RR(D);
}  // 1A = RR D	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(1B, RR_E) {
	RR(E);
}  // 1B = RR E	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(1C, RR_H) {
	RR(H);
}  // 1C = RR H	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(1D, RR_L) {
	RR(L);
}  // 1D = RR L	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(1E, RR_(HL)) {
	u8 r = cpu_read(HL);
	RR(r);
	cpu_write(HL, r);
}  // 1E = RR (HL)	 | Fg: Z 0 0 C | Sz: 2 | Cc: 16

INST_H(1F, RR_A) {
	RR(A);
}  // 1F = RR A	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(08, RRC_B) {
	RRC(B);
}  // 08 = RRC B	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(09, RRC_C) {
	RRC(C);
}  // 09 = RRC C	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(0A, RRC_D) {
	RRC(D);
}  // 0A = RRC D	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(0B, RRC_E) {
	RRC(E);
}  // 0B = RRC E	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(0C, RRC_H) {
	RRC(H);
}  // 0C = RRC H	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(0D, RRC_L) {
	RRC(L);
}  // 0D = RRC L	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(0E, RRC_(HL)) {
	u8 r = cpu_read(HL);
	RRC(r);
	cpu_write(HL, r);
}  // 0E = RRC (HL)	 | Fg: Z 0 0 C | Sz: 2 | Cc: 16

INST_H(0F, RRC_A) {
	RRC(A);
}  // 0F = RRC A	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(C0, SET_0_B) {
	SET(0, B);
}  // C0 = SET 0,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(C1, SET_0_C) {
	SET(0, C);
}  // C1 = SET 0,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(C2, SET_0_D) {
	SET(0, D);
}  // C2 = SET 0,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(C3, SET_0_E) {
	SET(0, E);
}  // C3 = SET 0,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(C4, SET_0_H) {
	SET(0, H);
}  // C4 = SET 0,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(C5, SET_0_L) {
	SET(0, L);
}  // C5 = SET 0,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(C6, SET_0_(HL)) {
	u8 r = cpu_read(HL);
	SET(0, r);
	cpu_write(HL, r);
}  // C6 = SET 0,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(C7, SET_0_A) {
	SET(0, A);
}  // C7 = SET 0,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(C8, SET_1_B) {
	SET(1, B);
}  // C8 = SET 1,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(C9, SET_1_C) {
	SET(1, C);
}  // C9 = SET 1,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(CA, SET_1_D) {
	SET(1, D);
}  // CA = SET 1,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(CB, SET_1_E) {
	SET(1, E);
}  // CB = SET 1,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(CC, SET_1_H) {
	SET(1, H);
}  // CC = SET 1,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(CD, SET_1_L) {
	SET(1, L);
}  // CD = SET 1,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(CE, SET_1_(HL)) {
	u8 r = cpu_read(HL);
	SET(1, r);
	cpu_write(HL, r);
}  // CE = SET 1,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(CF, SET_1_A) {
	SET(1, A);
}  // CF = SET 1,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(D0, SET_2_B) {
	SET(2, B);
}  // D0 = SET 2,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(D1, SET_2_C) {
	SET(2, C);
}  // D1 = SET 2,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(D2, SET_2_D) {
	SET(2, D);
}  // D2 = SET 2,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(D3, SET_2_E) {
	SET(2, E);
}  // D3 = SET 2,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(D4, SET_2_H) {
	SET(2, H);
}  // D4 = SET 2,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(D5, SET_2_L) {
	SET(2, L);
}  // D5 = SET 2,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(D6, SET_2_(HL)) {
	u8 r = cpu_read(HL);
	SET(2, r);
	cpu_write(HL, r);
}  // D6 = SET 2,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(D7, SET_2_A) {
	SET(2, A);
}  // D7 = SET 2,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(D8, SET_3_B) {
	SET(3, B);
}  // D8 = SET 3,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(D9, SET_3_C) {
	SET(3, C);
}  // D9 = SET 3,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(DA, SET_3_D) {
	SET(3, D);
}  // DA = SET 3,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(DB, SET_3_E) {
	SET(3, E);
}  // DB = SET 3,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(DC, SET_3_H) {
	SET(3, H);
}  // DC = SET 3,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(DD, SET_3_L) {
	SET(3, L);
}  // DD = SET 3,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(DE, SET_3_(HL)) {
	u8 r = cpu_read(HL);
	SET(3, r);
	cpu_write(HL, r);
}  // DE = SET 3,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(DF, SET_3_A) {
	SET(3, A);
}  // DF = SET 3,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(E0, SET_4_B) {
	SET(4, B);
}  // E0 = SET 4,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(E1, SET_4_C) {
	SET(4, C);
}  // E1 = SET 4,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(E2, SET_4_D) {
	SET(4, D);
}  // E2 = SET 4,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(E3, SET_4_E) {
	SET(4, E);
}  // E3 = SET 4,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(E4, SET_4_H) {
	SET(4, H);
}  // E4 = SET 4,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(E5, SET_4_L) {
	SET(4, L);
}  // E5 = SET 4,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(E6, SET_4_(HL)) {
	u8 r = cpu_read(HL);
	SET(4, r);
	cpu_write(HL, r);
}  // E6 = SET 4,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(E7, SET_4_A) {
	SET(4, A);
}  // E7 = SET 4,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(E8, SET_5_B) {
	SET(5, B);
}  // E8 = SET 5,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(E9, SET_5_C) {
	SET(5, C);
}  // E9 = SET 5,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(EA, SET_5_D) {
	SET(5, D);
}  // EA = SET 5,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(EB, SET_5_E) {
	SET(5, E);
}  // EB = SET 5,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(EC, SET_5_H) {
	SET(5, H);
}  // EC = SET 5,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(ED, SET_5_L) {
	SET(5, L);
}  // ED = SET 5,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(EE, SET_5_(HL)) {
	u8 r = cpu_read(HL);
	SET(5, r);
	cpu_write(HL, r);
}  // EE = SET 5,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(EF, SET_5_A) {
	SET(5, A);
}  // EF = SET 5,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(F0, SET_6_B) {
	SET(6, B);
}  // F0 = SET 6,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(F1, SET_6_C) {
	SET(6, C);
}  // F1 = SET 6,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(F2, SET_6_D) {
	SET(6, D);
}  // F2 = SET 6,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(F3, SET_6_E) {
	SET(6, E);
}  // F3 = SET 6,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(F4, SET_6_H) {
	SET(6, H);
}  // F4 = SET 6,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(F5, SET_6_L) {
	SET(6, L);
}  // F5 = SET 6,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(F6, SET_6_(HL)) {
	u8 r = cpu_read(HL);
	SET(6, r);
	cpu_write(HL, r);
}  // F6 = SET 6,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(F7, SET_6_A) {
	SET(6, A);
}  // F7 = SET 6,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(F8, SET_7_B) {
	SET(7, B);
}  // F8 = SET 7,B	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(F9, SET_7_C) {
	SET(7, C);
}  // F9 = SET 7,C	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(FA, SET_7_D) {
	SET(7, D);
}  // FA = SET 7,D	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(FB, SET_7_E) {
	SET(7, E);
}  // FB = SET 7,E	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(FC, SET_7_H) {
	SET(7, H);
}  // FC = SET 7,H	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(FD, SET_7_L) {
	SET(7, L);
}  // FD = SET 7,L	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(FE, SET_7_(HL)) {
	u8 r = cpu_read(HL);
	SET(7, r);
	cpu_write(HL, r);
}  // FE = SET 7,(HL)	 | Fg: - - - - | Sz: 2 | Cc: 16

INST_H(FF, SET_7_A) {
	SET(7, A);
}  // FF = SET 7,A	 | Fg: - - - - | Sz: 2 | Cc: 8

INST_H(20, SLA_B) {
	SLA(B);
}  // 20 = SLA B	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(21, SLA_C) {
	SLA(C);
}  // 21 = SLA C	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(22, SLA_D) {
	SLA(D);
}  // 22 = SLA D	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(23, SLA_E) {
	SLA(E);
}  // 23 = SLA E	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(24, SLA_H) {
	SLA(H);
}  // 24 = SLA H	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(25, SLA_L) {
	SLA(L);
}  // 25 = SLA L	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(26, SLA_(HL)) {
	u8 r = cpu_read(HL);
	SLA(r);
	cpu_write(HL, r);
}  // 26 = SLA (HL)	 | Fg: Z 0 0 C | Sz: 2 | Cc: 16

INST_H(27, SLA_A) {
	SLA(A);
}  // 27 = SLA A	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(28, SRA_B) {
	SRA(B);
}  // 28 = SRA B	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(29, SRA_C) {
	SRA(C);
}  // 29 = SRA C	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(2A, SRA_D) {
	SRA(D);
}  // 2A = SRA D	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(2B, SRA_E) {
	SRA(E);
}  // 2B = SRA E	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(2C, SRA_H) {
	SRA(H);
}  // 2C = SRA H	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(2D, SRA_L) {
	SRA(L);
}  // 2D = SRA L	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(2E, SRA_(HL)) {
	u8 r = cpu_read(HL);
	SRA(r);
	cpu_write(HL, r);
}  // 2E = SRA (HL)	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 16

INST_H(2F, SRA_A) {
	SRA(A);
}  // 2F = SRA A	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(38, SRL_B) {
	SRL(B);
}  // 38 = SRL B	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(39, SRL_C) {
	SRL(C);
}  // 39 = SRL C	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(3A, SRL_D) {
	SRL(D);
}  // 3A = SRL D	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(3B, SRL_E) {
	SRL(E);
}  // 3B = SRL E	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(3C, SRL_H) {
	SRL(H);
}  // 3C = SRL H	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(3D, SRL_L) {
	SRL(L);
}  // 3D = SRL L	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(3E, SRL_(HL)) {
	u8 r = cpu_read(HL);
	SRL(r);
	cpu_write(HL, r);
}  // 3E = SRL (HL)	 | Fg: Z 0 0 C | Sz: 2 | Cc: 16

INST_H(3F, SRL_A) {
	SRL(A);
}  // 3F = SRL A	 | Fg: Z 0 0 C | Sz: 2 | Cc: 8

INST_H(30, SWAP_B) {
	SWAP(B);
}  // 30 = SWAP B	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(31, SWAP_C) {
	SWAP(C);
}  // 31 = SWAP C	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(32, SWAP_D) {
	SWAP(D);
}  // 32 = SWAP D	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(33, SWAP_E) {
	SWAP(E);
}  // 33 = SWAP E	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(34, SWAP_H) {
	SWAP(H);
}  // 34 = SWAP H	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(35, SWAP_L) {
	SWAP(L);
}  // 35 = SWAP L	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

INST_H(36, SWAP_(HL)) {
	u8 r = cpu_read(HL);
	SWAP(r);
	cpu_write(HL, r);
}  // 36 = SWAP (HL)	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 16

INST_H(37, SWAP_A) {
	SWAP(A);
}  // 37 = SWAP A	 | Fg: Z 0 0 0 | Sz: 2 | Cc: 8

#pragma endregion

#pragma region GBZ80 Instruction Set
static Instruction * Instructions[] = {
	i00, i01, i02, i03, i04, i05, i06, i07, i08, i09, i0A, i0B, i0C, i0D, i0E, i0F, // 00
	i10, i11, i12, i13, i14, i15, i16, i17, i18, i19, i1A, i1B, i1C, i1D, i1E, i1F, // 10
	i20, i21, i22, i23, i24, i25, i26, i27, i28, i29, i2A, i2B, i2C, i2D, i2E, i2F, // 20
	i30, i31, i32, i33, i34, i35, i36, i37, i38, i39, i3A, i3B, i3C, i3D, i3E, i3F, // 30
	i40, i41, i42, i43, i44, i45, i46, i47, i48, i49, i4A, i4B, i4C, i4D, i4E, i4F, // 40
	i50, i51, i52, i53, i54, i55, i56, i57, i58, i59, i5A, i5B, i5C, i5D, i5E, i5F, // 50
	i60, i61, i62, i63, i64, i65, i66, i67, i68, i69, i6A, i6B, i6C, i6D, i6E, i6F, // 60
	i70, i71, i72, i73, i74, i75, i76, i77, i78, i79, i7A, i7B, i7C, i7D, i7E, i7F, // 70
	i80, i81, i82, i83, i84, i85, i86, i87, i88, i89, i8A, i8B, i8C, i8D, i8E, i8F, // 80
	i90, i91, i92, i93, i94, i95, i96, i97, i98, i99, i9A, i9B, i9C, i9D, i9E, i9F, // 90
	iA0, iA1, iA2, iA3, iA4, iA5, iA6, iA7, iA8, iA9, iAA, iAB, iAC, iAD, iAE, iAF, // A0
	iB0, iB1, iB2, iB3, iB4, iB5, iB6, iB7, iB8, iB9, iBA, iBB, iBC, iBD, iBE, iBF, // B0
	iC0, iC1, iC2, iC3, iC4, iC5, iC6, iC7, iC8, iC9, iCA, iCB, iCC, iCD, iCE, iCF, // C0
	iD0, iD1, iD2, iD3, iD4, iD5, iD6, iD7, iD8, iD9, iDA, iDB, iDC, iDD, iDE, iDF, // D0
	iE0, iE1, iE2, iE3, iE4, iE5, iE6, iE7, iE8, iE9, iEA, iEB, iEC, iED, iEE, iEF, // E0
	iF0, iF1, iF2, iF3, iF4, iF5, iF6, iF7, iF8, iF9, iFA, iFB, iFC, iFD, iFE, iFF, // F0
};

static Instruction * HighInstructions[] = {
	iCB00, iCB01, iCB02, iCB03, iCB04, iCB05, iCB06, iCB07, iCB08, iCB09, iCB0A, iCB0B, iCB0C, iCB0D, iCB0E, iCB0F, // 00
	iCB10, iCB11, iCB12, iCB13, iCB14, iCB15, iCB16, iCB17, iCB18, iCB19, iCB1A, iCB1B, iCB1C, iCB1D, iCB1E, iCB1F, // 10
	iCB20, iCB21, iCB22, iCB23, iCB24, iCB25, iCB26, iCB27, iCB28, iCB29, iCB2A, iCB2B, iCB2C, iCB2D, iCB2E, iCB2F, // 20
	iCB30, iCB31, iCB32, iCB33, iCB34, iCB35, iCB36, iCB37, iCB38, iCB39, iCB3A, iCB3B, iCB3C, iCB3D, iCB3E, iCB3F, // 30
	iCB40, iCB41, iCB42, iCB43, iCB44, iCB45, iCB46, iCB47, iCB48, iCB49, iCB4A, iCB4B, iCB4C, iCB4D, iCB4E, iCB4F, // 40
	iCB50, iCB51, iCB52, iCB53, iCB54, iCB55, iCB56, iCB57, iCB58, iCB59, iCB5A, iCB5B, iCB5C, iCB5D, iCB5E, iCB5F, // 50
	iCB60, iCB61, iCB62, iCB63, iCB64, iCB65, iCB66, iCB67, iCB68, iCB69, iCB6A, iCB6B, iCB6C, iCB6D, iCB6E, iCB6F, // 60
	iCB70, iCB71, iCB72, iCB73, iCB74, iCB75, iCB76, iCB77, iCB78, iCB79, iCB7A, iCB7B, iCB7C, iCB7D, iCB7E, iCB7F, // 70
	iCB80, iCB81, iCB82, iCB83, iCB84, iCB85, iCB86, iCB87, iCB88, iCB89, iCB8A, iCB8B, iCB8C, iCB8D, iCB8E, iCB8F, // 80
	iCB90, iCB91, iCB92, iCB93, iCB94, iCB95, iCB96, iCB97, iCB98, iCB99, iCB9A, iCB9B, iCB9C, iCB9D, iCB9E, iCB9F, // 90
	iCBA0, iCBA1, iCBA2, iCBA3, iCBA4, iCBA5, iCBA6, iCBA7, iCBA8, iCBA9, iCBAA, iCBAB, iCBAC, iCBAD, iCBAE, iCBAF, // A0
	iCBB0, iCBB1, iCBB2, iCBB3, iCBB4, iCBB5, iCBB6, iCBB7, iCBB8, iCBB9, iCBBA, iCBBB, iCBBC, iCBBD, iCBBE, iCBBF, // B0
	iCBC0, iCBC1, iCBC2, iCBC3, iCBC4, iCBC5, iCBC6, iCBC7, iCBC8, iCBC9, iCBCA, iCBCB, iCBCC, iCBCD, iCBCE, iCBCF, // C0
	iCBD0, iCBD1, iCBD2, iCBD3, iCBD4, iCBD5, iCBD6, iCBD7, iCBD8, iCBD9, iCBDA, iCBDB, iCBDC, iCBDD, iCBDE, iCBDF, // D0
	iCBE0, iCBE1, iCBE2, iCBE3, iCBE4, iCBE5, iCBE6, iCBE7, iCBE8, iCBE9, iCBEA, iCBEB, iCBEC, iCBED, iCBEE, iCBEF, // E0
	iCBF0, iCBF1, iCBF2, iCBF3, iCBF4, iCBF5, iCBF6, iCBF7, iCBF8, iCBF9, iCBFA, iCBFB, iCBFC, iCBFD, iCBFE, iCBFF, // F0
};

static u8 OPSize[] = {
	0, 2, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, // 00
	0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, // 10
	1, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, // 20
	1, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, // 30
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 40
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 50
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 60
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 70
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 80
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 90
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // A0
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // B0
	0, 0, 2, 2, 2, 0, 1, 0, 0, 0, 2, 1, 2, 2, 1, 0, // C0
	0, 0, 2, 0, 2, 0, 1, 0, 0, 0, 2, 0, 2, 0, 1, 0, // D0
	1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, // E0
	1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, // F0
};

const char * const OPName[] = {
	"NOP        ", "LD BC,d16  ", "LD (BC),A  ", "INC BC     ", "INC B      ", "DEC B      ", "LD B,d8    ", "RLCA       ", "LD (a16),SP", "ADD HL,BC  ", "LD A,(BC)  ", "DEC BC     ", "INC C      ", "DEC C      ", "LD C,d8    ", "RRCA       ", // 00
	"STOP 0     ", "LD DE,d16  ", "LD (DE),A  ", "INC DE     ", "INC D      ", "DEC D      ", "LD D,d8    ", "RLA        ", "JR r8      ", "ADD HL,DE  ", "LD A,(DE)  ", "DEC DE     ", "INC E      ", "DEC E      ", "LD E,d8    ", "RRA        ", // 10
	"JR NZ,r8   ", "LD HL,d16  ", "LD (HL+),A ", "INC HL     ", "INC H      ", "DEC H      ", "LD H,d8    ", "DAA        ", "JR Z,r8    ", "ADD HL,HL  ", "LD A,(HL+) ", "DEC HL     ", "INC L      ", "DEC L      ", "LD L,d8    ", "CPL        ", // 20
	"JR NC,r8   ", "LD SP,d16  ", "LD (HL-),A ", "INC SP     ", "INC (HL)   ", "DEC (HL)   ", "LD (HL),d8 ", "SCF        ", "JR C,r8    ", "ADD HL,SP  ", "LD A,(HL-) ", "DEC SP     ", "INC A      ", "DEC A      ", "LD A,d8    ", "CCF        ", // 30
	"LD B,B     ", "LD B,C     ", "LD B,D     ", "LD B,E     ", "LD B,H     ", "LD B,L     ", "LD B,(HL)  ", "LD B,A     ", "LD C,B     ", "LD C,C     ", "LD C,D     ", "LD C,E     ", "LD C,H     ", "LD C,L     ", "LD C,(HL)  ", "LD C,A     ", // 40
	"LD D,B     ", "LD D,C     ", "LD D,D     ", "LD D,E     ", "LD D,H     ", "LD D,L     ", "LD D,(HL)  ", "LD D,A     ", "LD E,B     ", "LD E,C     ", "LD E,D     ", "LD E,E     ", "LD E,H     ", "LD E,L     ", "LD E,(HL)  ", "LD E,A     ", // 50
	"LD H,B     ", "LD H,C     ", "LD H,D     ", "LD H,E     ", "LD H,H     ", "LD H,L     ", "LD H,(HL)  ", "LD H,A     ", "LD L,B     ", "LD L,C     ", "LD L,D     ", "LD L,E     ", "LD L,H     ", "LD L,L     ", "LD L,(HL)  ", "LD L,A     ", // 60
	"LD (HL),B  ", "LD (HL),C  ", "LD (HL),D  ", "LD (HL),E  ", "LD (HL),H  ", "LD (HL),L  ", "HALT       ", "LD (HL),A  ", "LD A,B     ", "LD A,C     ", "LD A,D     ", "LD A,E     ", "LD A,H     ", "LD A,L     ", "LD A,(HL)  ", "LD A,A     ", // 70
	"ADD A,B    ", "ADD A,C    ", "ADD A,D    ", "ADD A,E    ", "ADD A,H    ", "ADD A,L    ", "ADD A,(HL) ", "ADD A,A    ", "ADC A,B    ", "ADC A,C    ", "ADC A,D    ", "ADC A,E    ", "ADC A,H    ", "ADC A,L    ", "ADC A,(HL) ", "ADC A,A    ", // 80
	"SUB B      ", "SUB C      ", "SUB D      ", "SUB E      ", "SUB H      ", "SUB L      ", "SUB (HL)   ", "SUB A      ", "SBC A,B    ", "SBC A,C    ", "SBC A,D    ", "SBC A,E    ", "SBC A,H    ", "SBC A,L    ", "SBC A,(HL) ", "SBC A,A    ", // 90
	"AND B      ", "AND C      ", "AND D      ", "AND E      ", "AND H      ", "AND L      ", "AND (HL)   ", "AND A      ", "XOR B      ", "XOR C      ", "XOR D      ", "XOR E      ", "XOR H      ", "XOR L      ", "XOR (HL)   ", "XOR A      ", // A0
	"OR B       ", "OR C       ", "OR D       ", "OR E       ", "OR H       ", "OR L       ", "OR (HL)    ", "OR A       ", "CP B       ", "CP C       ", "CP D       ", "CP E       ", "CP H       ", "CP L       ", "CP (HL)    ", "CP A       ", // B0
	"RET NZ     ", "POP BC     ", "JP NZ,a16  ", "JP a16     ", "CALL NZ,a16", "PUSH BC    ", "ADD A,d8   ", "RST 00H    ", "RET Z      ", "RET        ", "JP Z,a16   ", "PREFIX CB  ", "CALL Z,a16 ", "CALL a16   ", "ADC A,d8   ", "RST 08H    ", // C0
	"RET NC     ", "POP DE     ", "JP NC,a16  ", "UNKN       ", "CALL NC,a16", "PUSH DE    ", "SUB d8     ", "RST 10H    ", "RET C      ", "RETI       ", "JP C,a16   ", "UNKN       ", "CALL C,a16 ", "UNKN       ", "SBC A,d8   ", "RST 18H    ", // D0
	"LDH (a8),A ", "POP HL     ", "LD (C),A   ", "UNKN       ", "UNKN       ", "PUSH HL    ", "AND d8     ", "RST 20H    ", "ADD SP,r8  ", "JP (HL)    ", "LD (a16),A ", "UNKN       ", "UNKN       ", "UNKN       ", "XOR d8     ", "RST 28H    ", // E0
	"LDH A,(a8) ", "POP AF     ", "LD A,(C)   ", "DI         ", "UNKN       ", "PUSH AF    ", "OR d8      ", "RST 30H    ", "LD HL,SP+r8", "LD SP,HL   ", "LD A,(a16) ", "EI         ", "UNKN       ", "UNKN       ", "CP d8      ", "RST 38H    ", // F0
	"RLC B      ", "RLC C      ", "RLC D      ", "RLC E      ", "RLC H      ", "RLC L      ", "RLC (HL)   ", "RLC A      ", "RRC B      ", "RRC C      ", "RRC D      ", "RRC E      ", "RRC H      ", "RRC L      ", "RRC (HL)   ", "RRC A      ", // 00
	"RL B       ", "RL C       ", "RL D       ", "RL E       ", "RL H       ", "RL L       ", "RL (HL)    ", "RL A       ", "RR B       ", "RR C       ", "RR D       ", "RR E       ", "RR H       ", "RR L       ", "RR (HL)    ", "RR A       ", // 10
	"SLA B      ", "SLA C      ", "SLA D      ", "SLA E      ", "SLA H      ", "SLA L      ", "SLA (HL)   ", "SLA A      ", "SRA B      ", "SRA C      ", "SRA D      ", "SRA E      ", "SRA H      ", "SRA L      ", "SRA (HL)   ", "SRA A      ", // 20
	"SWAP B     ", "SWAP C     ", "SWAP D     ", "SWAP E     ", "SWAP H     ", "SWAP L     ", "SWAP (HL)  ", "SWAP A     ", "SRL B      ", "SRL C      ", "SRL D      ", "SRL E      ", "SRL H      ", "SRL L      ", "SRL (HL)   ", "SRL A      ", // 30
	"BIT 0,B    ", "BIT 0,C    ", "BIT 0,D    ", "BIT 0,E    ", "BIT 0,H    ", "BIT 0,L    ", "BIT 0,(HL) ", "BIT 0,A    ", "BIT 1,B    ", "BIT 1,C    ", "BIT 1,D    ", "BIT 1,E    ", "BIT 1,H    ", "BIT 1,L    ", "BIT 1,(HL) ", "BIT 1,A    ", // 40
	"BIT 2,B    ", "BIT 2,C    ", "BIT 2,D    ", "BIT 2,E    ", "BIT 2,H    ", "BIT 2,L    ", "BIT 2,(HL) ", "BIT 2,A    ", "BIT 3,B    ", "BIT 3,C    ", "BIT 3,D    ", "BIT 3,E    ", "BIT 3,H    ", "BIT 3,L    ", "BIT 3,(HL) ", "BIT 3,A    ", // 50
	"BIT 4,B    ", "BIT 4,C    ", "BIT 4,D    ", "BIT 4,E    ", "BIT 4,H    ", "BIT 4,L    ", "BIT 4,(HL) ", "BIT 4,A    ", "BIT 5,B    ", "BIT 5,C    ", "BIT 5,D    ", "BIT 5,E    ", "BIT 5,H    ", "BIT 5,L    ", "BIT 5,(HL) ", "BIT 5,A    ", // 60
	"BIT 6,B    ", "BIT 6,C    ", "BIT 6,D    ", "BIT 6,E    ", "BIT 6,H    ", "BIT 6,L    ", "BIT 6,(HL) ", "BIT 6,A    ", "BIT 7,B    ", "BIT 7,C    ", "BIT 7,D    ", "BIT 7,E    ", "BIT 7,H    ", "BIT 7,L    ", "BIT 7,(HL) ", "BIT 7,A    ", // 70
	"RES 0,B    ", "RES 0,C    ", "RES 0,D    ", "RES 0,E    ", "RES 0,H    ", "RES 0,L    ", "RES 0,(HL) ", "RES 0,A    ", "RES 1,B    ", "RES 1,C    ", "RES 1,D    ", "RES 1,E    ", "RES 1,H    ", "RES 1,L    ", "RES 1,(HL) ", "RES 1,A    ", // 80
	"RES 2,B    ", "RES 2,C    ", "RES 2,D    ", "RES 2,E    ", "RES 2,H    ", "RES 2,L    ", "RES 2,(HL) ", "RES 2,A    ", "RES 3,B    ", "RES 3,C    ", "RES 3,D    ", "RES 3,E    ", "RES 3,H    ", "RES 3,L    ", "RES 3,(HL) ", "RES 3,A    ", // 90
	"RES 4,B    ", "RES 4,C    ", "RES 4,D    ", "RES 4,E    ", "RES 4,H    ", "RES 4,L    ", "RES 4,(HL) ", "RES 4,A    ", "RES 5,B    ", "RES 5,C    ", "RES 5,D    ", "RES 5,E    ", "RES 5,H    ", "RES 5,L    ", "RES 5,(HL) ", "RES 5,A    ", // A0
	"RES 6,B    ", "RES 6,C    ", "RES 6,D    ", "RES 6,E    ", "RES 6,H    ", "RES 6,L    ", "RES 6,(HL) ", "RES 6,A    ", "RES 7,B    ", "RES 7,C    ", "RES 7,D    ", "RES 7,E    ", "RES 7,H    ", "RES 7,L    ", "RES 7,(HL) ", "RES 7,A    ", // B0
	"SET 0,B    ", "SET 0,C    ", "SET 0,D    ", "SET 0,E    ", "SET 0,H    ", "SET 0,L    ", "SET 0,(HL) ", "SET 0,A    ", "SET 1,B    ", "SET 1,C    ", "SET 1,D    ", "SET 1,E    ", "SET 1,H    ", "SET 1,L    ", "SET 1,(HL) ", "SET 1,A    ", // C0
	"SET 2,B    ", "SET 2,C    ", "SET 2,D    ", "SET 2,E    ", "SET 2,H    ", "SET 2,L    ", "SET 2,(HL) ", "SET 2,A    ", "SET 3,B    ", "SET 3,C    ", "SET 3,D    ", "SET 3,E    ", "SET 3,H    ", "SET 3,L    ", "SET 3,(HL) ", "SET 3,A    ", // D0
	"SET 4,B    ", "SET 4,C    ", "SET 4,D    ", "SET 4,E    ", "SET 4,H    ", "SET 4,L    ", "SET 4,(HL) ", "SET 4,A    ", "SET 5,B    ", "SET 5,C    ", "SET 5,D    ", "SET 5,E    ", "SET 5,H    ", "SET 5,L    ", "SET 5,(HL) ", "SET 5,A    ", // E0
	"SET 6,B    ", "SET 6,C    ", "SET 6,D    ", "SET 6,E    ", "SET 6,H    ", "SET 6,L    ", "SET 6,(HL) ", "SET 6,A    ", "SET 7,B    ", "SET 7,C    ", "SET 7,D    ", "SET 7,E    ", "SET 7,H    ", "SET 7,L    ", "SET 7,(HL) ", "SET 7,A    ", // F0
};


#pragma endregion

#pragma endregion

///////////////// CPU /////////////////

void cpu_init() {
	A = GBC ? 0x11: 0x01;
	F = 0xB0, BC = 0x13, DE = 0xD8, HL = 0x014D, SP = 0xFFFE, PC = 0x100;
	IME = halted = halt_bug = IME_DELAY = double_speed = 0;
}

void cpu_run() { // run 1 loop (>= 1 M-cycle)
	u8 fflag = ioIF;
	
	u8 flag = fflag & read_ie();
	// TODO: add halt_bug in RST
	if (flag) {
		if (halted) {
			halted = 0;
			PC++;
		}
		if (IME) {
			sync(8);
			IME = 0;
			
			u8 log = 0;
			while (!(flag & (1 << log))) log++;
			
			ioIF = (fflag & (~(1 << log))) | 0xe0;
			
			if (halt_bug) halt_bug = 0, PC--; // Push the HALT addr
			PUSH16(PC);
			PC = 0x40 | (log << 3); // INT Vec jump // TODO: delay 1 M-cycle
		}
	}
	
	u8 sz;
	
	if ((sz = OPSize[fetch_opcode()])) {
		if (sz == 2) fetch_2operand();
		else fetch_1operand();
	}
	
	Instructions[OPCODE]();
	
	if (IME_DELAY & 1) IME = 1; // assumes that EI, EI, ..., EI will take effect at the end of the 2nd, and not the last
	IME_DELAY >>= 1;
}
